version: 0.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017
matrix:
  fast_finish: false
environment:
  PSGalleryApiKey:
    secure: X23r0Rpvuuv9YYJ9JGJVkAQ7SDHPslytk5uJxuNhF7dnNIAB8h6uIike18k/Icsz  
  DownloadBase:
    secure: tvDdT2DZMOgijvJd0Pvmuic+soMCi6cNrh+ndejvp0gb6vCTKWp3tbXNmoUi5kjzpdTZetFLWNKDuim/FJ0aVw==
  matrix:
  - SitecoreVersion: 920XP0
    InstallCommand: Install-Sitecore92
    ShouldDeploy: True
services:
- iis
- mssql2017
build_script:
- ps: >-
    .\test.ps1 -Prefix appveyor `
               -SitecoreVersion $Env:SitecoreVersion `
               -DownloadBase $Env:DownloadBase `
               -SqlAdminPassword 'Password12!' `
               -InstallCommand $Env:InstallCommand

deploy_script:
- ps: .\deploy.ps1